// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Js_mapperRt = require("bs-platform/lib/js/js_mapperRt.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Button = require("@material-ui/core/Button");
var Typography = require("@material-ui/core/Typography");

var jsMapperConstantArray = /* array */[
  /* tuple */[
    -925487250,
    "extendedFab"
  ],
  /* tuple */[
    -515484397,
    "contained"
  ],
  /* tuple */[
    -387916264,
    "raised"
  ],
  /* tuple */[
    -28821822,
    "outlined"
  ],
  /* tuple */[
    3502759,
    "fab"
  ],
  /* tuple */[
    781662169,
    "flat"
  ],
  /* tuple */[
    936573133,
    "text"
  ]
];

function variantToJs(param) {
  return Js_mapperRt.binarySearch(7, param, jsMapperConstantArray);
}

function variantFromJs(param) {
  return Js_mapperRt.revSearch(7, jsMapperConstantArray, param);
}

function make(variant, onClick, children) {
  var tmp = { };
  var tmp$1 = Belt_Option.map(variant, (function (v) {
          return Js_mapperRt.binarySearch(7, v, jsMapperConstantArray);
        }));
  if (tmp$1 !== undefined) {
    tmp.variant = Caml_option.valFromOption(tmp$1);
  }
  if (onClick !== undefined) {
    tmp.onClick = Caml_option.valFromOption(onClick);
  }
  return ReasonReact.wrapJsForReason(Button.default, tmp, children);
}

var Button$1 = /* module */[
  /* variantToJs */variantToJs,
  /* variantFromJs */variantFromJs,
  /* make */make
];

var jsMapperConstantArray$1 = /* array */[
  /* tuple */[
    -181429991,
    "subtitle1"
  ],
  /* tuple */[
    -181429990,
    "subtitle2"
  ],
  /* tuple */[
    23241,
    "h1"
  ],
  /* tuple */[
    23242,
    "h2"
  ],
  /* tuple */[
    23243,
    "h3"
  ],
  /* tuple */[
    23244,
    "h4"
  ],
  /* tuple */[
    23245,
    "h5"
  ],
  /* tuple */[
    23246,
    "h6"
  ],
  /* tuple */[
    921686863,
    "body1"
  ],
  /* tuple */[
    921686864,
    "body2"
  ]
];

function variantToJs$1(param) {
  return Js_mapperRt.binarySearch(10, param, jsMapperConstantArray$1);
}

function variantFromJs$1(param) {
  return Js_mapperRt.revSearch(10, jsMapperConstantArray$1, param);
}

function make$1(variant, children) {
  var tmp = { };
  var tmp$1 = Belt_Option.map(variant, (function (v) {
          return Js_mapperRt.binarySearch(10, v, jsMapperConstantArray$1);
        }));
  if (tmp$1 !== undefined) {
    tmp.variant = Caml_option.valFromOption(tmp$1);
  }
  return ReasonReact.wrapJsForReason(Typography.default, tmp, children);
}

var Typography$1 = /* module */[
  /* variantToJs */variantToJs$1,
  /* variantFromJs */variantFromJs$1,
  /* make */make$1
];

exports.Button = Button$1;
exports.Typography = Typography$1;
/* ReasonReact Not a pure module */
